site_name: My Project Documentation
nav:
  - Inicio: index.md
  - Instalación: about.md
  - Views:
    - Vista de inicio: index_view.md
    - Vista de administrador: admin_view.md
    - Vista de resultados: results_view.md
    - Vista de usuario: user_view.md

theme: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
